- title: Walls
  fa_class: fa fa-paint-roller
  text: Painting walls can be challenging so, let us do it for you. Our professional painting techniques will have your walls looking brand new.

- title: Trim
  fa_class: fa fa-brush
  text: A sloppy trim job looks awful. We know how to paint straight lines for beautiful looking baseboards, windows, and casings. 

- title: Doors
  fa_class: fa fa-door-closed
  text: First impressions are important! We restore faded and chipping doors. The sun is harsh so, let us keep your exterior doors looking fresh.

- title: Patching
  fa_class: fa fa-band-aid
  text: We repair all types of damaged drywall such as nail holes, doorknob holes, or even entire sheets of drywall. Our repairs are smooth and ready to paint!

- title: Color Matching
  fa_class: fa fa-eye-dropper
  text: Love your current colors? Then let us perform a color match and freshen up your walls. Painting the same color costs less!

- title: Prep Work
  fa_class: fa fa-crop-alt
  text: Excellent prepping will result in a great looking finish. We sand, caulk, and prime everything before we paint anything. 

- title: Stairs
  fa_class: fab fa-firstdraft
  text: Stairs can be a dangerous place to maneuver. Often we use specialty ladders to paint these areas safely. Don't risk falling; call us!

- title: Hard-to-reach Areas
  fa_class: fa fa-angle-double-up
  text: Are you the DIY type, but can't quite reach those high spots? We will gladly bring whatever equipment it takes to get the job done.