- title: Walls
  fa_class: fa fa-paint-roller
  text: Dolorem possimus assumenda aliquid aliquam cursus itaque! Assumenda diamlorem, cum, nobis, cursus, accumsan accumsan, nam lacus nostra aptent! Alias, suscipit tempora iusto omnis.
- title: Trim
  fa_class: fa fa-brush
  text: Dolorem possimus assumenda aliquid aliquam cursus itaque! Assumenda diamlorem, cum, nobis, cursus, accumsan accumsan, nam lacus nostra aptent! Alias, suscipit tempora iusto omnis.
- title: Doors
  fa_class: fa fa-door-closed
  text: Dolorem possimus assumenda aliquid aliquam cursus itaque! Assumenda diamlorem, cum, nobis, cursus, accumsan accumsan, nam lacus nostra aptent! Alias, suscipit tempora iusto omnis.
- title: Patch Nail Holes
  fa_class: fa fa-hammer
  text: Dolorem possimus assumenda aliquid aliquam cursus itaque! Assumenda diamlorem, cum, nobis, cursus, accumsan accumsan, nam lacus nostra aptent! Alias, suscipit tempora iusto omnis.
- title: Color Matching
  fa_class: fa fa-eye-dropper
  text: Dolorem possimus assumenda aliquid aliquam cursus itaque! Assumenda diamlorem, cum, nobis, cursus, accumsan accumsan, nam lacus nostra aptent! Alias, suscipit tempora iusto omnis.
- title: Caulking
  fa_class: fa fa-grip-lines-vertical
  text: Dolorem possimus assumenda aliquid aliquam cursus itaque! Assumenda diamlorem, cum, nobis, cursus, accumsan accumsan, nam lacus nostra aptent! Alias, suscipit tempora iusto omnis.
- title: Foyer
  fa_class: fa fa-door-open
  text: Dolorem possimus assumenda aliquid aliquam cursus itaque! Assumenda diamlorem, cum, nobis, cursus, accumsan accumsan, nam lacus nostra aptent! Alias, suscipit tempora iusto omnis.
- title: Hard-to-reach Areas
  fa_class: fa fa-angle-double-up
  text: Dolorem possimus assumenda aliquid aliquam cursus itaque! Assumenda diamlorem, cum, nobis, cursus, accumsan accumsan, nam lacus nostra aptent! Alias, suscipit tempora iusto omnis.